# Generated by Django 5.2.6 on 2025-10-23 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_delete_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
