# Generated by Django 5.2.6 on 2026-03-06 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_supervisorrequest'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='supervisorrequest',
            unique_together={('student', 'supervisor')},
        ),
    ]
