# Generated by Django 5.2.6 on 2026-03-06 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_alter_supervisorrequest_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('user_registered', 'User Registered'), ('user_approved', 'User Approved'), ('user_rejected', 'User Rejected'), ('ccv_uploaded', 'CCV Uploaded'), ('ccv_student_uploaded', 'Student CCV Uploaded'), ('activity_submitted', 'Activity Submitted'), ('activity_approved', 'Activity Approved'), ('activity_rejected', 'Activity Rejected'), ('supervisor_requested', 'Supervisor Requested'), ('supervisor_approved', 'Supervisor Approved'), ('supervisor_rejected', 'Supervisor Rejected'), ('publication_added', 'Publication Added'), ('publication_deleted', 'Publication Deleted'), ('project_updated', 'Project Updated'), ('profile_updated', 'Profile Updated'), ('edi_updated', 'EDI Profile Updated'), ('consent_updated', 'Consent Updated'), ('report_uploaded', 'Report Uploaded'), ('report_deleted', 'Report Deleted'), ('other', 'Other')], max_length=30)),
                ('target_type', models.CharField(blank=True, max_length=50, null=True)),
                ('target_id', models.PositiveIntegerField(blank=True, null=True)),
                ('summary', models.CharField(blank=True, max_length=500, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', 'created_at'], name='config_audi_action_c1627d_idx'), models.Index(fields=['user', 'created_at'], name='config_audi_user_id_2e4b92_idx')],
            },
        ),
    ]
