# Generated by Django 5.2.6 on 2026-03-07 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentnotification',
            name='request_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
