# Generated by Django 5.2.6 on 2026-03-08 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0005_studentnotification_request_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='funding',
            name='role',
            field=models.CharField(blank=True, choices=[('pi', 'Principal Investigator'), ('co_pi', 'Co-Investigator'), ('pa', 'Principal Applicant'), ('co_app', 'Co-applicant'), ('other', 'Other')], help_text="Researcher's role on this grant", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='funding',
            name='status',
            field=models.CharField(blank=True, choices=[('submitted', 'Submitted'), ('awarded', 'Awarded'), ('rejected', 'Rejected')], help_text='Outcome of this grant application', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('user_registered', 'User Registered'), ('user_approved', 'User Approved'), ('user_rejected', 'User Rejected'), ('ccv_uploaded', 'CCV Uploaded'), ('ccv_student_uploaded', 'Student CCV Uploaded'), ('activity_submitted', 'Activity Submitted'), ('activity_approved', 'Activity Approved'), ('activity_rejected', 'Activity Rejected'), ('supervisor_requested', 'Supervisor Requested'), ('supervisor_approved', 'Supervisor Approved'), ('supervisor_rejected', 'Supervisor Rejected'), ('publication_added', 'Publication Added'), ('publication_deleted', 'Publication Deleted'), ('project_updated', 'Project Updated'), ('profile_updated', 'Profile Updated'), ('edi_updated', 'EDI Profile Updated'), ('consent_updated', 'Consent Updated'), ('report_uploaded', 'Report Uploaded'), ('report_deleted', 'Report Deleted'), ('other', 'Other')], max_length=50),
        ),
        migrations.AddIndex(
            model_name='funding',
            index=models.Index(fields=['start_date', 'end_date'], name='config_fund_start_d_77482a_idx'),
        ),
        migrations.AddIndex(
            model_name='funding',
            index=models.Index(fields=['status'], name='config_fund_status_85fb93_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['start_date', 'end_date'], name='config_proj_start_d_653567_idx'),
        ),
        migrations.AddIndex(
            model_name='publication',
            index=models.Index(fields=['publication_date'], name='config_publ_publica_d82739_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['graduation_date'], name='config_stud_graduat_9e349c_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['start_date'], name='config_stud_start_d_41c96e_idx'),
        ),
    ]
