# Generated by Django 5.2.6 on 2026-03-08 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0006_funding_role_funding_status_alter_auditlog_action_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='activity',
            unique_together={('researcher', 'external_id')},
        ),
        migrations.AlterUniqueTogether(
            name='education',
            unique_together={('researcher', 'external_id')},
        ),
        migrations.AlterUniqueTogether(
            name='funding',
            unique_together={('researcher', 'external_id')},
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('researcher', 'external_id')},
        ),
        migrations.AlterUniqueTogether(
            name='publication',
            unique_together={('researcher', 'external_id')},
        ),
        migrations.AlterUniqueTogether(
            name='recognition',
            unique_together={('researcher', 'external_id')},
        ),
        migrations.CreateModel(
            name='PublicationAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_authors', to='config.publication')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='config.studentprofile')),
            ],
            options={
                'unique_together': {('publication', 'student')},
            },
        ),
    ]
