# Generated by Django 5.2.6 on 2026-03-12 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0007_alter_activity_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='funding',
            name='amount_to_ibme',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Portion of funding received by this researcher/institution', max_digits=15, null=True),
        ),
    ]
