# Generated by Django 5.2.6 on 2026-03-15 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0008_funding_amount_to_ibme'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='funding_kept_by_unb',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount of funding retained by UNB after overhead/indirect costs', max_digits=12, null=True),
        ),
    ]
