# Generated by Django 5.2.6 on 2026-03-19 03:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0010_conference_activity_conference'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tagged_members',
            field=models.ManyToManyField(blank=True, help_text='RIMS users tagged as HQP or collaborators on this project', related_name='tagged_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
