# Generated by Django 5.2.6 on 2026-03-23 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0012_activity_deleted_at_activity_deleted_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupervisionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=500, null=True)),
                ('student_name', models.CharField(max_length=255)),
                ('institution', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('degree_type', models.CharField(blank=True, choices=[('bachelors', "Bachelor's"), ('masters_thesis', "Master's Thesis"), ('masters_non_thesis', "Master's Non-Thesis"), ('doctorate', 'Doctorate'), ('postdoc', 'Post-doctorate'), ('research_associate', 'Research Associate')], max_length=30, null=True)),
                ('supervision_role', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, choices=[('in_progress', 'In Progress'), ('completed', 'Completed')], max_length=20, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('degree_start_date', models.DateField(blank=True, null=True)),
                ('degree_end_date', models.DateField(blank=True, null=True)),
                ('expected_date', models.DateField(blank=True, null=True)),
                ('thesis_title', models.TextField(blank=True, null=True)),
                ('present_position', models.CharField(blank=True, max_length=500, null=True)),
                ('present_org', models.CharField(blank=True, max_length=500, null=True)),
                ('residency_status', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('researcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervision_records', to='config.researcherprofile')),
            ],
            options={
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['degree_type'], name='config_supe_degree__f007df_idx'), models.Index(fields=['status'], name='config_supe_status_fefa56_idx'), models.Index(fields=['start_date'], name='config_supe_start_d_478524_idx')],
                'unique_together': {('researcher', 'external_id')},
            },
        ),
    ]
