# Generated by Django 5.2.6 on 2026-03-23 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0013_supervisionrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='funding',
            name='parent_record_id',
            field=models.CharField(blank=True, db_index=True, max_length=500, null=True),
        ),
    ]
