# Generated by Django 5.2.6 on 2026-03-25 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0014_funding_parent_record_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='funding',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funding_breakdown', to='config.project'),
        ),
    ]
