# Generated by Django 5.2.6 on 2026-03-25 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0015_funding_project'),
    ]

    operations = [
    ]
