# Generated by Django 5.2.6 on 2026-03-25 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0016_populate_funding_project_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('awarded', 'Awarded'), ('completed', 'Completed'), ('pending', 'Pending'), ('submitted', 'Submitted'), ('rejected', 'Rejected')], default='awarded', max_length=20),
        ),
    ]
