# Generated by Django 5.2.6 on 2026-03-25 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0017_alter_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmember',
            name='partner_type',
            field=models.CharField(blank=True, choices=[('academic', 'Academic'), ('industry', 'Industry'), ('community', 'Community'), ('government', 'Government'), ('other', 'Other')], help_text='Type of collaborator or partner', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='projectmember',
            name='is_academic_collaborator',
            field=models.BooleanField(default=False, help_text='Legacy — use partner_type instead'),
        ),
    ]
