# Generated by Django 5.2.6 on 2026-03-26 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0018_projectmember_partner_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funding',
            name='parent_record_id',
        ),
    ]
