# Generated by Django 5.2.6 on 2026-03-26 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0019_remove_funding_parent_record_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='race_ethnicity',
            field=models.CharField(blank=True, choices=[('white', 'White / European descent'), ('black', 'Black / African descent'), ('east_asian', 'East Asian'), ('south_asian', 'South Asian'), ('southeast_asian', 'Southeast Asian'), ('latin', 'Latin American / Hispanic'), ('middle_eastern', 'Middle Eastern / North African'), ('indigenous', 'Indigenous (other than First Nations/Métis/Inuit)'), ('mixed', 'Two or more ethnicities'), ('other', 'Other'), ('prefer_not', 'Prefer not to say')], max_length=50, null=True, verbose_name='Race / Ethnicity'),
        ),
    ]
