# Generated by Django 5.2.6 on 2026-03-26 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0020_add_race_ethnicity_to_student_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='category',
            field=models.CharField(blank=True, choices=[('conference', 'Conference'), ('knowledge_mobilization', 'Knowledge Mobilization'), ('media', 'Media'), ('academic', 'Academic'), ('other', 'Other')], max_length=50, null=True),
        ),
    ]
