# Generated by Django 5.2.6 on 2026-03-28 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0021_alter_activity_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='manually_overridden',
            field=models.BooleanField(default=False, help_text='If True, CCV re-uploads will not overwrite funding fields or status/role'),
        ),
    ]
