# Generated by Django 5.2.6 on 2026-03-28 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0023_alter_auditlog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='program_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
