# Generated by Django 5.2.6 on 2026-03-29 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0024_project_program_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='funding',
            name='currency',
            field=models.CharField(blank=True, choices=[('CAD', 'CAD'), ('USD', 'USD')], default='CAD', max_length=10),
        ),
        migrations.AddField(
            model_name='project',
            name='currency',
            field=models.CharField(blank=True, choices=[('CAD', 'CAD'), ('USD', 'USD')], default='CAD', max_length=10),
        ),
    ]
