# Generated by Django 5.2.6 on 2026-03-30 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0025_funding_currency_project_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='force_password_change',
            field=models.BooleanField(default=False),
        ),
    ]
