# Generated by Django 5.2.6 on 2026-03-30 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0028_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('user_registered', 'User Registered'), ('user_approved', 'User Approved'), ('user_rejected', 'User Rejected'), ('user_login', 'User Login'), ('login_failed', 'Login Failed'), ('login_pending', 'Login Attempt — Pending Account'), ('ccv_uploaded', 'CCV Uploaded'), ('ccv_student_uploaded', 'Student CCV Uploaded'), ('activity_submitted', 'Activity Submitted'), ('activity_approved', 'Activity Approved'), ('activity_rejected', 'Activity Rejected'), ('activity_deleted', 'Activity Deleted'), ('supervisor_requested', 'Supervisor Requested'), ('supervisor_approved', 'Supervisor Approved'), ('supervisor_rejected', 'Supervisor Rejected'), ('publication_added', 'Publication Added'), ('publication_updated', 'Publication Updated'), ('publication_deleted', 'Publication Deleted'), ('project_created', 'Project Created'), ('project_updated', 'Project Updated'), ('project_deleted', 'Project Deleted'), ('hqp_tagged', 'HQP Tagged'), ('hqp_untagged', 'HQP Untagged'), ('profile_updated', 'Profile Updated'), ('edi_updated', 'EDI Profile Updated'), ('consent_updated', 'Consent Updated'), ('report_uploaded', 'Report Uploaded'), ('report_deleted', 'Report Deleted'), ('other', 'Other'), ('user_created_by_admin', 'User Created by Admin'), ('password_changed', 'Password Changed'), ('password_reset_by_admin', 'Password Reset by Admin')], max_length=50),
        ),
    ]
