# Generated by Django 5.2.6 on 2026-03-30 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0029_alter_auditlog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='temp_password_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
