# Generated by Django 5.2.6 on 2026-03-31 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0030_customuser_temp_password_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisionrecord',
            name='department',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supervisionrecord',
            name='manually_overridden',
            field=models.BooleanField(default=False, help_text='If True, CCV re-uploads will not overwrite manually edited fields'),
        ),
    ]
