# Generated by Django 5.2.6 on 2026-03-31 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0031_supervisionrecord_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisionrecord',
            name='linked_student',
            field=models.ForeignKey(blank=True, help_text='Linked RIMS student account if registered', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervision_records', to='config.studentprofile'),
        ),
    ]
