# Generated by Django 5.2.6 on 2026-04-04 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0032_supervisionrecord_linked_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='co_supervisors',
            field=models.ManyToManyField(blank=True, related_name='co_supervised_students', to='config.researcherprofile'),
        ),
    ]
