# Generated by Django 5.2.6 on 2026-04-04 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0033_studentprofile_co_supervisors'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='manually_overridden',
            field=models.BooleanField(default=False, help_text='If True, CCV re-uploads will not overwrite manually edited fields'),
        ),
    ]
