# Generated by Django 5.2.6 on 2026-04-05 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0035_alter_auditlog_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategicObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='customuser',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('inactive', 'Inactive')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='activity',
            name='objectives',
            field=models.ManyToManyField(blank=True, related_name='activities', to='config.strategicobjective'),
        ),
    ]
