# Generated by Django 5.2.6 on 2026-04-11 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0036_strategicobjective_alter_customuser_approval_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='funding',
            name='grant_total',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Full project Total Funding from CCV, regardless of researcher's portion", max_digits=15, null=True),
        ),
    ]
