# Generated by Django 5.2.6 on 2026-04-12 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0037_funding_grant_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='totp_setup_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
