# Generated by Django 5.2.6 on 2026-04-12 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0038_customuser_totp_setup_started_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
    ]
